version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
      - AWS_REGION=us-east-1
      - MODEL_PLUG_URL=http://model-server-plug:8501/v1/models/plug
#      - MODEL_LAMP_URL=http://model-server-lamp:8501/v1/models/lamp
    depends_on:
      - model-server-plug
#      - model-server-lamp
    networks:
      - ia_net

  model-server-plug:
    image: tensorflow/serving
    ports:
      - "8501:8501"  # expõe porta 8501 para acesso ao modelo plug
    volumes:
      - ./prediction/app/models/plug:/models/plug
    environment:
      - MODEL_NAME=plug
    networks:
      - ia_net

#  model-server-lamp:
#    image: tensorflow/serving
#    ports:
#      - "8502:8501"  # expõe 8502 no host, mapeado para 8501 no container
#    volumes:
#      - ./prediction/app/models/lamp:/models/lamp
#    environment:
#      - MODEL_NAME=lamp
#    networks:
#      - ia_net

networks:
  ia_net:
