version: "3.8"

services:
  api:
    build:
      context: ./app
    ports:
      - "5000:5000"
    environment:
      - MODEL_URL=http://model-server:8501/v1/models/model:predict
    depends_on:
      - model-server
    networks:
      - ia_net

  model-server:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./model/v1:/models/model
    environment:
      - MODEL_NAME=model
    networks:
      - ia_net

networks:
  ia_net:
