version: "3.8"

services:
  api:
    build:
      context: ./app
    ports:
      - "5000:5000"
    environment:
      - MODEL_PLUG_URL=http://model-server-plug:8501/v1/models/plug
      - MODEL_LAMPADA_URL=http://model-server-lampada:8501/v1/models/lampada
    depends_on:
      - model-server-plug
      - model-server-lampada
    networks:
      - ia_net

  model-server-plug:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./model-plug:/models/plug
    environment:
      - MODEL_NAME=plug
    networks:
      - ia_net

  model-server-lampada:
    image: tensorflow/serving
    ports:
      - "8502:8501"
    volumes:
      - ./model-lampada:/models/lampada
    environment:
      - MODEL_NAME=lampada
    networks:
      - ia_net

networks:
  ia_net:
